# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5aa4026dbb0a387ce2fa4b9e8b9fec1641b030fedce7e67396c66ce71ed56be6825303ba6aa676deb35bf0e7fde113ab093d9215758a41e9209d7a5ab3c4c95

test:
  secret_key_base: 4748b676695751a625dd92e7910017095d00e3e73a4ffbb9168d92fe3236326d13331b64ec3ef01f021182d0877744a1c44d4a1e85dd791626f633913fa51ba8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
